### ISSUE TITLE
Repository has no license file.

### ISSUE THREAD

**Issue by allanwright** [tunip/docker-filebot#1]
Hi Tunip

I'm interested in creating a docker image that combines deluge with the filebot cli.  I've tested this with a modified version of your dockerfile and it appears to work quite well.  I was wondering if you could please inform me whether or not your decision to leave out a license file in the repository is intentional?  Based on the github documentation, the lack of a license file means that standard copyright laws apply, meaning that you hold full rights to the repository.  Could you please advise if this is your intention?  If not, would you be interested in adding a license file to the repository so that I can determine my rights, if any, to modify the work you have already done in my own github repository?

**Comment by tunip** [comment]
Hi allanwright,

I added a license file to the repository.

**Comment by allanwright** [comment]
Awesome, thanks so much Tunip!
